name: Sync branch1 with main

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: |
          set -euo pipefail

          git pull --rebase

          git branch -D branch1
          git checkout -b branch1
          git push --set-upstream origin branch1 -f

          git checkout main

          # Update a dummy file to avoid branch mismatches on triggers.
          # https://github.com/slsa-framework/example-package/issues/44
          DATE="$(date)"
          echo "$DATE" > ./e2e/dummy
          git add ./e2e/dummy
          git commit -m "syncing branch1 - $DATE"
          git push
